name: Pipeline

on:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  miri:
    name: "Run Miri"

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Test with Miri
        run: cargo miri test

  build-and-test:
    name: "Build and Test"
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        features: ["", "serde"]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --features "${{ matrix.features }}"
    - name: Test
      run: cargo test --verbose --features "${{ matrix.features }}"
